server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    passwort: provider
    url: jdbc:mysql://localhost:3306/teste
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        fortmat-sql: true
    show-sql: true
